locale: en

formats:
  datetime:
    DATE:
      weekday: short
      day: numeric
      month: short
      year: numeric
    SHORT_DATE:
      day: 2-digit
      month: 2-digit
      year: numeric
    TIME:
      hour: 2-digit
      minute: 2-digit
      timeZoneName: short
      hour12: false

map:
  options:
    style: mapbox://styles/mapbox/light-v10
    center: [1.6, 42.55]
    zoom: 10
    maxPitch: 0
  controls:
    navigation:
      position: top-right
    scale:
      position: bottom-right

markers:
  ripple:
    IDLE:
      size: 20px
    ACTIVE:
      size: 200px

filters:
  search: ''
  options:
    range:
      min: 0
      max: 10
      step: 1
      showTooltip: focus
      lazy: true
      merge: 1
      options:
        margin: 1


footer:
  learn:
    - name: Seismology
      url: '#seismology'
    - name: Seismic Survey
      url: https://andorra-ri.github.io/enquesta-sismica/
      target: blank
    - name: News
      url: '#news'
    - name: FAQ
      url: '#faq'

  about:
    - name: Company
      url: '#company'
    - name: Careers
      url: '#carrers'
    - name: Press
      url: '#press'
    - name: Terms & Policies
      url: '#terms'
      target: blank

  contact:
    - name: Send a message
      url: 'mailto:terratremols@ari.ad'
    - name: Request a demo
      url: gsfhgdhfg
    - name: +376 742 630
      url: 'tel:+376-742-630'

api:
  seisms:
    endpoint: seism
    schema: seismology
