locale: en

surveyURL: https://enquesta.terratremols.ad/

newsfeed:
  dateLimit:
    days: -14

formats:
  DATE:
    weekday: short
    day: numeric
    month: long
    year: numeric
    timeZone: Europe/Andorra
  TIME:
    hour: 2-digit
    minute: 2-digit
    timeZone: Europe/Andorra
    hour12: false

map:
  style: mapbox://styles/mapbox/light-v10
  center: [1.6, 42.55]
  zoom: 10
  minZoom: 7
  maxZoom: 13
  scrollZoom: false
  customAttribution: Dades proporcionades per <a href="https://www.icgc.cat/ca/Ciutada/Explora-Catalunya/Terratremols" target="blank">Institut Cartogràfic i Geològic de Catalunya</a>
  controls:
    Navigation:
      position: top-right
      showCompass: false
    Scale:
      position: bottom-right

layers:
  SEISMS:
    name: seisms
    layers:
      - name: seisms
        type: circle
        paint:
          circle-color: '#d34'
          circle-radius: 2
          circle-stroke-color: '#d34'
          circle-stroke-opacity: 0.15
          circle-stroke-width: [interpolate, [exponential, 2], [zoom],
            0, 0,
            13, [/, [/, [get, magnitude], 0.005], [cos, ['*', 42.5, [/, [pi], 180]]]]]

markers:
  ripple:
    IDLE:
      size: 20px
    ACTIVE:
      size: 200px

seismology:
  resources:
    - id: basic
      icon: bookmark
      url: https://www.terratremols.ad/docs/conceptes_basics_terratremols.pdf
    - id: andorra
      icon: focus
      url: https://www.terratremols.ad/docs/sismicitat_andorra.pdf
    - id: seismicity
      icon: pulse
      url: https://www.terratremols.ad/docs/activitat_sismica.pdf
    - id: hazards
      icon: shield-cross
      url: https://www.terratremols.ad/docs/risc_sismic_andorra.pdf


footer:
  learn:
    - id: nav.seismology
      url: '#seismology'
    - id: nav.tips
      url: https://www.protecciocivil.ad/info-riscos/sismes
    - id: nav.faq
      url: '#faq'

  act:
    - id: nav.survey
      url: https://andorra-ri.github.io/enquesta-sismica/
      target: blank
    - id: nav.links
      url: '#links'
    - id: nav.privacy_policy
      url: https://ari.ad/politica-privadesa
      target: blank

  info:
    - id: nav.news
      url: '#news'
    - id: contact.send_message
      url: 'mailto:terratremols@ari.ad'
    - id: +376 742 630
      url: 'tel:+376-742-630'

locations:
  # Andorra
  Canillo: [1.601101, 42.566381]
  Encamp: [1.583651, 42.535970]
  Ordino: [1.533006, 42.556897]
  La Massana: [1.515489, 42.545048]
  Andorra la Vella: [1.521882, 42.507472]
  Sant Julia de Lòria: [1.492432, 42.468866]
  Escaldes-Engordany: [1.539143, 42.510778]
  Pas de la Casa: [1.733257, 42.542628]

  # Espanya
  Ós de Civís: [1.439186, 42.510714]
  La Seu d'Urgell: [1.462358, 42.357864]
  Puigcerdà: [1.927148, 42.431164]
  Olot: [2.484584, 42.183091]
  Figueres: [2.960659, 42.267383]
  Berga: [1.846074, 42.104306]
  Ponts: [1.186381, 41.915625]
  Tremp: [0.896047, 42.167213]
  Sort: [1.131098, 42.413085]
  Vielha e Mijaran: [0.795597, 42.701706]

  # França
  Foix: [1.605249, 42.965325]
  Saint-Girons: [1.147406, 42.982382]
  Ax-les-Thermes: [1.841654, 42.719727]
  Prades: [2.423464, 42.617847]
  Perpignan: [2.893915, 42.699649]
